bitbag_multi_vendor_marketplace_product_listings:
    resource: 'admin/product_listing.yml'
bitbag_multi_vendor_marketplace_vendor:
    resource: 'admin/vendor.yml'
bitbag_multi_vendor_marketplace_vendor_verify:
    resource: "admin/vendor_verify.yml"
bitbag_multi_vendor_marketplace_vendor_disable:
    resource: "admin/vendor_disable.yml"
bitbag_multi_vendor_marketplace_vendor_enable:
    resource: "admin/vendor_enable.yml"
