imports:
    - { resource: "resources.yml" }
    - { resource: "grids.yml" }
    - { resource: "state_machine/state_machine.yml" }
    - { resource: '@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/services.xml' }
