imports:
  - { resource: '@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/services.xml' }
  - { resource: '@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/resources.yml' }
  - { resource: '@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/grids.yml' }
  - { resource: "@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/resources/sylius_mailer.yml"}
