imports:
    - { resource: "@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/resources/conversation.yml" }
    - { resource: "@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/resources/conversation_category.yml" }
    - { resource: "@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/resources/vendor.yml" }
    - { resource: "@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/resources/conversation_message.yml" }
    - { resource: "@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/resources/vendor_user.yml" }
    - { resource: "@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/resources/customer.yml"}
    - { resource: "@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/resources/multi_vendor_market_place_product_listing.yml"}
