#imports:
#  - { resource: "resources/customer.yml"}
#  - { resource: "resources/vendor.yml"}
#  - { resource: '@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/resources/multi_vendor_market_place_product_listing.yml' }
#  - { resource: '@BitBagSyliusMultiVendorMarketplacePlugin/Resources/config/resources/sylius_mailer.yml'}
