sylius_resource:
  resource:
    sylius_multi_vendor_marketplace_plugin.product_listing:
      driver: doctrine/orm
      classes:
        model: Bitbag\SyliusMultiVendorMarketplacePlugin\Entity\ProductListing
