vendor_registration:
  resource: "routes/vendor_register_form.yml"
  prefix: /{_locale}
  requirements:
    _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
vendor_profile:
  resource: "routes/vendor_profile.yml"
  prefix: /{_locale}
  requirements:
    _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
