winzou_state_machine:
    mvm_conversation:
        class: "%mvm.model.conversation.class%"
        property_path: status
        graph: mvm_conversation
        state_machine_class: "%sylius.state_machine.class%"
        states:
            open: ~
            closed: ~
        transitions:
            close:
                from: [open]
                to: closed
