sylius_grid:
  grids:
    bitbag_sylius_multi_vendor_marketplace_plugin_admin_product_listing:
      driver:
        name: doctrine/orm
        options:
          class: BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ProductListing
      fields:
        name:
          type: string
          label: sylius.ui.name
