sylius_grid:
  templates:
    action:
      details: '@BitBagSyliusMultiVendorMarketplacePlugin/Grid/Action/product_details.html.twig'
    filter:
      product_listing_status: '@BitBagSyliusMultiVendorMarketplacePlugin/Grid/Filter/product_listing_status.html.twig'
  grids:
    bitbag_sylius_multi_vendor_marketplace_plugin_admin_product_listing:
      filters:
        search:
          type: string
          form_options:
            type: contains
          options:
            fields: ['name', 'code']
        status:
          type: product_listing_status
          label: bitbag_sylius_multi_vendor_marketplace_plugin.ui.status
      driver:
        name: doctrine/orm
        options:
          class: BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ProductListing\ProductListing
      fields:
        code:
          type: string
          label: bitbag_sylius_multi_vendor_marketplace_plugin.ui.code
#        publishedAt:
#          type: datetime
#          label: bitbag_sylius_multi_vendor_marketplace_plugin.ui.published_at
#        verifiedAt:
#          type: datetime
#          label: bitbag_sylius_multi_vendor_marketplace_plugin.ui.verified_at
#        status:
#          type: string
#          label: bitbag_sylius_multi_vendor_marketplace_plugin.ui.status
      actions:
        item:
          details:
            type: details
            label: bitbag_sylius_multi_vendor_marketplace_plugin.ui.details
            options:
              link:
                route: bitbag_sylius_multi_vendor_marketplace_plugin_admin_product_listing_show
                parameters:
                  id: resource.id
