bitbag_sylius_multi_vendor_marketplace_plugin_admin_product_listing:
  resource: |
    alias: bitbag_sylius_multi_vendor_marketplace_plugin.product_listing
    section: admin
    templates: SyliusAdminBundle:Crud
    except: ['show']
    redirect: update
    grid: bitbag_sylius_multi_vendor_marketplace_plugin_admin_product_listing
  type: sylius.resource
