app_admin_product_listing:
  resource: |
    alias: bitbag_sylius_multi_vendor_marketplace_plugin.product_listing
    section: admin
    templates: '@SyliusAdmin/Crud'
    except: ['show', 'create']
    redirect: index
    grid: bitbag_sylius_multi_vendor_marketplace_plugin_admin_product_listing
  type: sylius.resource
